config/routes.rb
Rails.application.routes.draw do
  root "sub#index"

  resources :subs do
    resources :topics  
  end

  resources :topics do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub.rb
class Sub < ApplicationRecord
    has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :sub
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
                          # except: [:index, :new, :create]
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  def index
    @subs = Sub.all
  end

  def show
  end

  def new
    @sub = Sub.new
    render partial: "form"
  end

  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to subs_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @sub.update(sub_params)
      # redirect_to subs_path(@sub) or a shortcut of ....
      redirect_to sub_path(@sub)
    else
      render :edit
    end
  end

  def destroy
    @sub.destroy
    redirect_to subs_path
    # redirect_to root_path - you could change that to root but if you change the root it could be problematic
  end

  private
    def sub_params
      params.require(:sub).permit(:name)  
    end

    def set_sub
      # localhost:3000/subs/:id
      @sub = Sub.find(params[:id])
      #this will now call this method at the start of every method so you can delete it from edit update destroy show
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
        before_action :set_sub 
        before_action :set_topic, only: [:show, :edit, :update, :destroy]
      
        def index
          @topics = @sub.topics
        end
      
        def show
        end
      
        def new
          @topic = @sub.topics.new
          render partial: "form"
        end
      
        def create
          @topic = @sub.topics.new(topic_params)
      
          if @topic.save
            redirect_to sub_topic_path(@sub, @topic)
            # redirect_to [@sub, @topic] same thing just shorthand see rails routes
          else
            render partial: "form"
          end
        end
      
        def edit
          render partial: "form"
        end
      
        def update
          if @topic.update(topic_params)
            redirect_to [@sub, @topic] # see create right above if this doesn't make sense
          else
            render :edit
          end
        end
      
        def destroy
          @topic.destroy
          redirect_to sub_topics_path(@sub) # this is wrong on the lecture!!! if there is a sub_:id on the params field(middle field) you have to pass it in your method
        end
      
        private
          def set_sub
            @sub = Sub.find(params[:sub_id])
          end
      
          def set_topic
            @topic = Topic.find(params[:id])
          end
      
          def topic_params
            params.require(:topic).permit(:name, :body)
          end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr />
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/index.html.erb
<h1>Click a Sub To View Content</h1>
<%= link_to 'Create a new sub', new_sub_path %>
<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.name, sub_path(sub) %></li>
  <% end %>
</ul>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br />
<%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/topics/_form.html.erb
<h1><%= @topic.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/topics/index.html.erb
<h1>Click a Topic To View Content</h1>
<%= link_to 'Create a new topic', new_sub_topic_path(@sub) %>
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, [@sub, topic] %></li>
  <% end %>
</ul>

app/views/topics/show.html.erb
<h1><%= @sub.name %> - <%= @topic.name %></h1>
<p><%= @topic.body %></p>
<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back To Topics', sub_topics_path(@sub) %>